# Generated by Django 2.1.7 on 2019-04-23 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('prof', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(max_length=40)),
                ('times', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('departement', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursematchapp.Course'),
        ),
    ]
