# Generated by Django 2.1.7 on 2019-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursematch_auth', '0002_auto_20190421_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_url',
            field=models.CharField(default='profile1.svg', max_length=50),
        ),
    ]
