# Generated by Django 2.1.7 on 2019-04-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursematchapp', '0001_initial'),
        ('coursematch_auth', '0003_student_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='coursematchapp.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='friends',
            field=models.ManyToManyField(related_name='_student_friends_+', to='coursematch_auth.Student'),
        ),
    ]
