# Generated by Django 2.1.7 on 2019-04-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursematchapp', '0001_initial'),
        ('coursematch_auth', '0004_auto_20190422_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(to='coursematchapp.Class'),
        ),
    ]
