# Generated by Django 2.1.7 on 2019-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursematch_auth', '0005_student_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='friends',
        ),
        migrations.AddField(
            model_name='student',
            name='following',
            field=models.ManyToManyField(related_name='_student_following_+', to='coursematch_auth.Student'),
        ),
    ]
