import Browser
import Html exposing (..)
import Browser.Navigation exposing (load)
import Html.Events exposing (onClick)
import Html.Attributes exposing (..)
import Http

main = 
 Browser.element { init = init, update = update, subscriptions = \_ -> Sub.none, view = view }

-- Change root URL as needed to route requests
rootUrl = "https://mac1xa3.ca/e/kostiukb/"

-- Model 
type alias Model = {}

type Msg = LoginButtonPressed       -- Login Button clicked
        | SignUpButtonPressed       -- Signup Button clicked
        | GetLoginResponse (Result Http.Error String )  -- Retrieve the login response from backend


init : () -> ( Model, Cmd Msg )
init _= ( {}, Cmd.none )

-- Send authentication request to see if user is already logged in
loginGetAuth : Model -> Cmd Msg
loginGetAuth model = Http.get { 
        url = rootUrl ++ "coursematchauth/isauth/"
        , expect = Http.expectString GetLoginResponse
    }

-- Update
update : Msg -> Model -> ( Model, Cmd Msg )
update msg model = case msg of
    LoginButtonPressed -> ( model, loginGetAuth model )

    SignUpButtonPressed -> ( model, load (rootUrl ++ "coursematch/static/signup.html"))

    GetLoginResponse result ->
        case result of
            -- Skip the login and go straight to home if user is loggin in
            Ok "Authenticated" -> ( {}, load (rootUrl ++ "coursematch/static/home.html"))
            -- Otherwise go to the login page
            Ok _ -> ( {}, load (rootUrl ++ "coursematch/static/login.html"))

            Err error -> ( {}, load (rootUrl ++ "coursematch/static/login.html"))

view : Model -> Html Msg
view model = div []
    [ node "link" [ href "vendor/bootstrap/css/bootstrap.min.css", rel "stylesheet" ]
        []
    , node "link" [ href "vendor/fontawesome-free/css/fontawesome.min.css", rel "stylesheet" ]
        []
    , node "link" [ href "https://fonts.googleapis.com/css?family=Poppins:300,400,600", rel "stylesheet" ]
        []
    , node "link" [ href "vendor/lightbox2/css/lightbox.css", rel "stylesheet" ]
        []
    , node "link" [ href "css/fontastic.css", rel "stylesheet" ]
        []
    , node "link" [ href "css/style.default.css", id "theme-stylesheet", rel "stylesheet" ]
        []
    , node "link" [ href "css/custom.css", rel "stylesheet" ]
        []
    , node "link" [ href "img/favicon.png", rel "shortcut icon" ]
        []
    , header [ class "header", id "top" ]
        [ nav [ class "navbar navbar-expand-lg fixed-top" ]
            [ div [ class "container" ]
                [ a [ class "navbar-brand", href "#" ]
                    [ img [ alt "", class "img-fluid", src "img/favicon.png" ]
                        []
                    , text "Course Match"
                    ]
                , div [ class "collapse navbar-collapse", id "navbarSupportedContent" ]
                    [ ul [ class "navbar-nav ml-auto" ]
                        [ li [ class "nav-item" ]
                            [ a [ class "nav-link", href "#top" ]
                                [ text "Home" ]
                            ]
                        , li [ class "nav-item" ]
                            [ a [ class "nav-link", href "#model" ]
                                [ text "Model" ]
                            ]
                        , li [ class "nav-item" ]
                            [ a [ class "nav-link", href "#footer" ]
                                [ text "Contact" ]
                            ]
                        , li [ class "nav-item" ]
                            [ a [ class "nav-link", href "signup.html" ]
                                [ text "Sign Up" ]
                            ]
                        ]
                    , a [ class "btn btn-primary navbar-btn ml-0 ml-lg-3", href "#", onClick LoginButtonPressed ]
                        [ text "Login" ]
                    ]
                ]
            ]
        ]
    , section [ class "hero" ]
        [ div [ class "container mb-5" ]
            [ div [ class "row align-items-center" ]
                [ div [ class "col-lg-6" ]
                    [ h1 [ class "hero-heading mb-0" ]
                        [ b []
                            [ text "Course Match" ]
                        ]
                    , div [ class "row" ]
                        [ div [ class "col-lg-10" ]
                            [ p [ class "lead text-muted mt-4 mb-4" ]
                                [ text "McMaster's first, free online class matching service.                " ]
                            , p [ class "lead text-muted mt-4 mb-4" ]
                                [ text "Find classes, compare & share shedules with friends, create groups and so much more!                  " ]
                            ]
                        ]
                    , a [ class "btn btn-primary", href "#", onClick SignUpButtonPressed ]
                        [ text "Get Started!" ]
                    ]
                , div [ class "col-lg-6" ]
                    [ img [ alt "...", class "hero-image img-fluid d-none d-lg-block", src "img/undraw_book_lover_mkck.svg" ]
                        []
                    ]
                ]
            ]
        ]
    , section [ id "model" ]
        [ div [ class "container" ]
            [ div [ class "text-center" ]
                [ h2 []
                    [ text "All your classes in one simple interface " ]
                , p [ class "lead text-muted mt-2" ]
                    [ text "Keep it simple with our online portal." ]
                , a [ class "btn btn-primary", href "#specs" ]
                    [ text "Learn More" ]
                ]
            , div [ class "row" ]
                [ div [ class "col-lg-7 mx-auto mt-5" ]
                    [ img [ alt "", class "intro-image img-fluid", src "img/illustration-1.svg" ]
                        []
                    ]
                ]
            ]
        ]
    , section [ class "bg-primary text-white" ]
        [ div [ class "container" ]
            [ div [ class "text-center" ]
                [ h2 []
                    [ text "Do great things together" ]
                , div [ class "row" ]
                    [ div [ class "col-lg-9 mx-auto" ]
                        [ p [ class "lead text-white mt-2" ]
                            [ text "Keep track of what classes your friends are taking, create friend groups,                ping classmates for a switch, compare schedules etc.              " ]
                        , p [ class "lead text-white mt-2" ]
                            [ text "Do it all online through "
                            , b []
                                [ text "Course Match" ]
                            , text "!              "
                            ]
                        ]
                    ]
                , a [ class "btn btn-outline-light", href "#specs" ]
                    [ text "Learn More" ]
                ]
            ]
        ]
    , section [ id "specs" ]
        [ div [ class "container" ]
            [ div [ class "text-center" ]
                [ h2 []
                    [ text "Features" ]
                , div [ class "row" ]
                    [ div [ class "col-lg-8 mx-auto" ]
                        [ p [ class "lead text-muted mt-2" ]
                            [ b []
                                [ text "Course Match" ]
                            , text "offers everything a student could want when picking and swapping classes.                With our innovative features, never be lost.              "
                            ]
                        ]
                    ]
                ]
            , div [ class "integrations mt-5" ]
                [ div [ class "row" ]
                    [ div [ class "col-lg-4" ]
                        [ div [ class "box text-center" ]
                            [ div [ class "icon d-flex align-items-end" ]
                                [ img [ alt "...", class "img-fluid", src "img/monitor.svg" ]
                                    []
                                ]
                            , h3 [ class "h4" ]
                                [ text "Online Portal" ]
                            , p [ class "text-small font-weight-light" ]
                                [ text "Everything online with our web portal, simply connect with your macID.                " ]
                            ]
                        ]
                    , div [ class "col-lg-4" ]
                        [ div [ class "box text-center" ]
                            [ div [ class "icon d-flex align-items-end" ]
                                [ img [ alt "...", class "img-fluid", src "img/target.svg" ]
                                    []
                                ]
                            , h3 [ class "h4" ]
                                [ text "Personalized" ]
                            , p [ class "text-small font-weight-light" ]
                                [ text "Create and manage your custom class schedule by semester.                " ]
                            ]
                        ]
                    , div [ class "col-lg-4" ]
                        [ div [ class "box text-center" ]
                            [ div [ class "icon d-flex align-items-end" ]
                                [ img [ alt "...", class "img-fluid", src "img/chat.svg" ]
                                    []
                                ]
                            , h3 [ class "h4" ]
                                [ text "Message" ]
                            , p [ class "text-small font-weight-light" ]
                                [ text "Ping friends & classmates to coordinate your schedules before the deadline.                " ]
                            ]
                        ]
                    , div [ class "col-lg-4" ]
                        [ div [ class "box text-center" ]
                            [ div [ class "icon d-flex align-items-end" ]
                                [ img [ alt "...", class "img-fluid", src "img/idea.svg" ]
                                    []
                                ]
                            , h3 [ class "h4" ]
                                [ text "Find" ]
                            , p [ class "text-small font-weight-light" ]
                                [ text "See what classes your friends are taking, making for an easy swap.                " ]
                            ]
                        ]
                    , div [ class "col-lg-4" ]
                        [ div [ class "box text-center" ]
                            [ div [ class "icon d-flex align-items-end" ]
                                [ img [ alt "...", class "img-fluid", src "img/coffee-cup.svg" ]
                                    []
                                ]
                            , h3 [ class "h4" ]
                                [ text "Compare" ]
                            , p [ class "text-small font-weight-light" ]
                                [ text "Compare your schedule against other faster than making coffee.                " ]
                            ]
                        ]
                    , div [ class "col-lg-4" ]
                        [ div [ class "box text-center" ]
                            [ div [ class "icon d-flex align-items-end" ]
                                [ img [ alt "...", class "img-fluid", src "img/pen.svg" ]
                                    []
                                ]
                            , h3 [ class "h4" ]
                                [ text "UX & UI" ]
                            , p [ class "text-small font-weight-light" ]
                                [ text "Beautiful and intuitive layout and user design, making it effortless to use.                " ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    , footer [ class "main-footer", id "footer" ]
        [ div [ class "container" ]
            [ div [ class "row" ]
                [ div [ class "col-lg-3 mb-5 mb-lg-0" ]
                    [ h4 [ class "footer-heading" ]
                        [ text "Course Match" ]
                    ]
                , div [ class "col-lg-5 mb-5 mb-lg-0" ]
                    [ h5 [ class "footer-heading" ]
                        [ text "Contact" ]
                    , p []
                        [ text "Contact us at coursematch@coursematch.ca" ]
                    , p []
                        [ text "Or call us at 905-757-4444" ]
                    ]
                , div [ class "col-lg-4 mb-5 mb-lg-0" ]
                    [ h5 [ class "footer-heading" ]
                        [ text "Author" ]
                    , p []
                        [ text "Course Match is made by Benjamin Kostiuk, a first-year computer science student at McMaster." ]
                    ]
                ]
            ]
        , div [ class "copyrights" ]
            [ div [ class "container" ]
                [ div [ class "row" ]
                    [ div [ class "col-lg-6 text-center text-lg-left" ]
                        [ p [ class "copyrights-text mb-3 mb-lg-0" ]
                            [ text "Course Match © All rights reserved." ]
                        ]
                    ]
                ]
            ]
        ]
    ]

